name: CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Simulação de deploy
        run: echo "🚀 Simulando deploy para produção..."

      - name: Finalizado
        run: echo "Deploy simulado com sucesso!"
