name: CI Workflow

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Simulação de build
        run: echo "Rodando build/testes..."

      - name: Finalizado
        run: echo "CI executado com sucesso!"
