name: Discord Notification on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "📣 Nova Pull Request criada ou atualizada! 🚀 Vamos revisar!"
